config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import (HomePageView, RegisterView, LoginView, CourseDetailView,
                    AddCourseView, UpdateCourseView, ServiceView, ServiceDetailView, TeacherView, TeacherDetailView)

app_name = 'main'

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('register', RegisterView.as_view(), name="register"),
    path('login', LoginView.as_view(), name="kirish"),
    path('course/<str:slug>', CourseDetailView.as_view(), name="detail"),
    path('add_course', AddCourseView.as_view(), name="add_course"),
    path('course/<int:pk>/edit', UpdateCourseView.as_view(), name="update_course"),
    path('service/', ServiceView.as_view(), name="services"),
    path('service_detail/<int:pk>/', ServiceDetailView.as_view(), name='service_detail'),
    path('teachers/', TeacherView.as_view(), name='teachers'),
   path('teacher/<int:pk>/', TeacherDetailView.as_view(), name='teacher_detail'),

]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User
from django.urls import reverse
from django.core.validators import FileExtensionValidator
from PIL import Image
from django.db import models



# Create your models here.

class User(AbstractUser):
    phone = models.CharField(max_length=13, blank=True,  db_index=True)
    auth_code = models.CharField(max_length=6, blank=True)

    # def get_absolute_url(self):
    #     print(self)
    #     return reverse("main:account", kwargs={"id": self.id})

    def __str__(self) -> str:
        return f"{self.username}"


class Category(models.Model):
    title = models.CharField(max_length=15)

    def __str__(self) -> str:
        return f"{self.title}"


class Tag(models.Model):
    title = models.CharField(max_length=15)

    def __str__(self) -> str:
        return f"{self.title}"




class Course(models.Model):
    LANGUAGES = (
        ('uz', 'O\'zbekcha'),
        ('ru', 'Ruscha'),
        ('en', 'Inglizcha'),
    )
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    description = models.TextField()
    duration = models.DurationField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)  # 100.00
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name="courses")
    created_at = models.DateTimeField(verbose_name="Boshlanish vaqti")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Yangilanish vaqti")
    language = models.CharField(max_length=100, blank=True, choices=LANGUAGES)
    rating = models.PositiveBigIntegerField(verbose_name="Rating", default=0)
    image = models.ImageField(upload_to="images", blank=True)
    tags = models.ManyToManyField('Tag', verbose_name="tags")

    class Meta:
        ordering = ['-rating']

    def save(self, *args, **kwargs):
        # Call the parent save method to save the object
        super().save(*args, **kwargs)

        if self.image:
            img = Image.open(self.image.path)

            # Resize the image to 150x220
            img = img.resize((150, 220), Image.ANTIALIAS)
            img.save(self.image.path)


# -------------------------------------------------------------------

class Header(models.Model):
    message = models.CharField(max_length=150)
    facebook = models.CharField(max_length=30)
    twitter = models.CharField(max_length=30)
    youtube = models.CharField(max_length=30)
    linkedin = models.CharField(max_length=30)
    logo = models.ImageField(upload_to="header/logo/")
    address = models.CharField(max_length=150)
    phone1 = models.CharField(max_length=15)
    phone2 = models.CharField(max_length=15)
    email1 = models.EmailField()
    email2 = models.EmailField()

    def __str__(self):
        return f"{self.message}"


class HeaderImage(models.Model):
    service = models.CharField(max_length=100)
    content = models.CharField(max_length=255)
    header = models.ForeignKey(Header, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='header/images/')


class Service(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()
    image = models.ImageField(upload_to="service/", help_text="O'lcham: 160x250 px")
    book_image = models.ImageField(upload_to="book/image/", help_text="O'lcham 371x202 px")
    created_at = models.DateTimeField(auto_now_add=True)


class ServiceBook(models.Model):
    service = models.ForeignKey(Service, on_delete=models.PROTECT)
    file = models.FileField(upload_to="book/file/", validators=[
        FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])
    ])


class Teachers(models.Model):
    title = models.CharField(max_length=255)
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to="teachers/images/", help_text="O'lcham 372x325 px")
    description = models.TextField()
    age = models.PositiveIntegerField()

main/forms.py
from .models import *
from django import forms


class CourseForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Course
        fields = ['title', 'description', 'duration', 'price', 'category', 'language', 'tags', 'image']

main/views.py
import datetime
from typing import Any
from django.http import FileResponse, JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from django.views import View
from .models import User, Course, Category, Tag, Header, HeaderImage, Service, ServiceBook, Teachers
from django.contrib.messages import warning, success
from .utils import send_verification_email
from django.contrib.auth import authenticate, login, logout
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .forms import CourseForm

# Create your views here.


class HomePageView(ListView):
    model = Course
    template_name = 'main/index.html'
    context_object_name = 'courses'
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        try:
            header = Header.objects.first()
            context['header'] = header
            header_images = HeaderImage.objects.filter(header=header)
            context['header_images'] = header_images

            services = Service.objects.all()[:4]
            context['services'] = services
        except:
            pass
        return context


class RegisterView(View):
    def get(self, request):
        return render(request, 'register.html')

    def post(self, request):
        username = request.POST['username']
        email = request.POST.get('email')
        email = request.POST.get('email')
        password = request.POST.get('password')
        password_confirm = request.POST.get('password_confirm')
        phone = request.POST.get('phone')

        if password != password_confirm:
            warning(request, 'Password confirmation is incorrect')
            return redirect(reverse('main:register'))
        if User.objects.filter(username=username).exists():
            warning(request, 'User already registered')
            return redirect(reverse('main:register'))
        user = User.objects.create_user(username=username,
                                        email=email,
                                        password=password,
                                        phone=phone, is_active=False)
        send_verification_email(user)
        login(request, user)
        success(request, 'User  registered')
        return redirect(reverse("main:kirish"))


class LoginView(View):
    def get(self, request):
        return render(request, 'registration/login.html', {"success": True})

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        if not User.objects.filter(username=username).exists():
            warning(request, 'User does not exist')
            return redirect(reverse('main:kirish'))
        user = User.objects.get(username=username)
        if not user.check_password(password):
            warning(request, 'Password is incorrect')
            return redirect(reverse('main:kirish'))
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse('main:home'))
        warning(request, 'Error')
        return redirect(reverse('main:kirish'))


class CourseDetailView(DetailView):
    model = Course
    template_name = 'course_single.html'
    context_object_name = 'course'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        data = super().get_context_data(**kwargs)
        data['tags'] = Tag.objects.all()
        return data


import os


class AddCourseView(View):
    model = Course
    fields = "__all__"  # ['title','created_at', 'description', 'duration', 'price', 'category', 'language', 'tags', 'image']
    template_name = 'course_add.html'
    success_url = "/"

    def get(self, request):
        path = os.getcwd()
        file = open(f"{path}/main/forms.py", 'rb')
        return JsonResponse({'success': True})
        form = CourseForm()
        return render(request, self.template_name, {'form': form, 'button': 'Add'})

    def post(self, request):
        form = CourseForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            success(request, 'Course added successfully')
            return redirect(self.success_url)
        else:
            warning(request, 'Course adding failed')
            return render(request, self.template_name, {'form': form})


class UpdateCourseView(View):
    model = Course
    fields = "__all__"  # ['title','created_at', 'description', 'duration', 'price', 'category', 'language', 'tags', 'image']
    template_name = 'course_add.html'
    success_url = "/"

    def get(self, request, pk):
        lang = request.COOKIES.get('language')
        button = 'Yangilash'
        if lang == 'en':
            button = 'Update'
        if lang == 'ru':
            button = 'Обновить'

        course = Course.objects.get(pk=pk)
        form = CourseForm(instance=course)
        response = render(request, self.template_name, {'form': form, 'button': button})
        expiry_time = datetime.datetime.now() + datetime.timedelta(hours=2)
        response.set_cookie('language', "uz", 7200)
        return response

    def post(self, request, pk):
        course = Course.objects.get(pk=pk)
        title = request.POST.get('title')
        course.title = title
        course.save()

        # form = CourseForm(request.POST, request.FILES, instance=course)
        # if form.is_valid():
        #     form.save()
        #     success(request, 'Course added successfully')
        #     return redirect(self.success_url)
        # else:
        #     warning(request, 'Course adding failed')
        #     return render(request, self.template_name, {'form': form})

# --------------------------------------------------------


class ServiceView(View):
    def get(self, request):
        services = Service.objects.all()
        latest_services = Service.objects.order_by('-id')[:3]  
        header = Header.objects.first()
        header_images = HeaderImage.objects.filter(header=header)

        context = {
            "services": services,
            "header": header,
            "latest_services": latest_services,  
            "header_images": header_images,
        }
        return render(request, "main/service.html", context)




class ServiceDetailView(View):
    def get(self, request, pk):
        service = get_object_or_404(Service, pk=pk)
       
        context = {
            "service": service,
        }
        return render(request, "main/service_detail.html", context)
    

class TeacherView(View):
    def get(self, request):
        teachers = Teachers.objects.all()
        context = {
            "teachers": teachers
        }
        return render(request, "main/teachers.html", context)



class TeacherDetailView(View):
    def get(self, request, pk):
        teacher = get_object_or_404(Teachers, pk=pk)
       
        context = {
            "teacher": teacher,
        }
        return render(request, "main/teacher_detail.html", context)
    

main/templates/main/index.html
{% extends 'base.html' %}

{% block content %}

<!--edu form wrapper Start-->
{% include 'main/components/_form_wrapper.html' %}
<!--edu form wrapper end-->

<!--edu books wrapper Start-->
{% include 'main/components/_books_wrapper.html' %}
<!--edu books wrapper End-->

<!--edu counter wrapper Start-->
{% include 'main/components/_counter_wrapper.html' %}
<!--edu counter wrapper End-->

<!--edu course wrapper Start-->
{% include 'main/components/_course_wrapper.html' %}
<!--edu course wrapper End-->

<!--edu gallery wrapper Start-->
{% include 'main/components/_gallery_wrapper.html' %}
<!--edu gallery wrapper End-->

<!--edu team wrapper Start-->
{% include 'main/components/_team_wrapper.html' %}
<!--edu team wrapper End-->

<!--edu Blog wrapper Start-->
{% include 'main/components/_blog_wrapper.html' %}
<!--edu Blog wrapper End-->

<!--edu testimonial wrapper Start-->
{% include 'main/components/_testimonial_wrapper.html' %}
<!--edu testimonial wrapper End -->

<!--edu partner wrapper Start-->
{% include 'main/components/_partner_wrapper.html' %}
<!--edu partner wrapper End-->

<!--edu letter wrapper Start-->
{% include 'main/components/_letter_wrapper.html' %}
<!--edu letter wrapper End-->

{% endblock content %}

main/templates/main/service.html
{% extends 'base.html' %}

{% block slider %}
{% endblock slider %}

{% block content %}
    <!-- inner header wrapper start -->
    <div class="page_title_section float_left">
        <div class="page_header">
            <div class="container">
                <div class="row">
                    <!-- section_heading start -->
                    <div class="col-lg-12 col-md-12 col-12 col-sm-12">
                        <h1>Services</h1>
                    </div>
                    <div class="col-lg-12 col-md-12 col-12 col-sm-12">
                        <div class="sub_title_section">
                            <ul class="sub_title">
                                <li><a href="#">Home</a> &nbsp;&nbsp;&nbsp; &gt; &nbsp;&nbsp;</li>
                                <li>Services</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- inner header wrapper end -->
    
    <!-- blog wrapper start -->
    <div class="blog_wrapper float_left">
        <div class="container">
            <div class="row">
                <div class="col-xl-8 col-lg-8 col-md-12 col-sm-12 col-xs-12">
                    <div class="row">
                        {% for service in services %}
                        <div class="col-md-6">
                            <div class="blog-post-wrapper iner_blog">
                                <div class="post-thumbnail">
                                    <img src="{{ service.image.url }}" class="img-responsive" alt="Image">
                                </div>
                                <div class="blog-content edu_service_header">
                                    <header class="entry-header">
                                        <h4 class="entry-title edu_service_heading">
                                            <a href="{% url 'main:service_detail' pk=service.pk %}">{{ service.title }}</a>
                                        </h4>
                                    </header>
                                    <div class="entry-content">
                                        <p>{{ service.content|truncatewords:20 }}</p>
                                    </div>
                                    <a href="{% url 'main:service_detail' pk=service.pk %}" class="blog_read">Read More</a>
                                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                
                <!-- Sidebar -->
                <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-xs-12 right_sidebar blog_single_sidebar">
                    <!-- Search Form -->
                    <div class="sidebar_widget float_left">
                        <div class="widget_heading">
                            <h2>Search feed</h2>
                        </div>
                        <form class="search_form" role="search">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Search...">
                            </div>
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                    
                    <!-- Latest Posts -->
                    <div class="sidebar_widget float_left">
                        <div class="widget_heading">
                            <h2>Latest Posts</h2>
                        </div>
                        {% for service in latest_services %}
                            <div class="blog_wrapper22 float_left">
                                <div class="blog_image">
                                    <img src="{{ service.image.url }}" class="img-responsive" alt="blog_img1" style="height: 100px; width: 80px;" />
                                </div>
                                <div class="blog_text">
                                    <h5><a href="#">{{ service.content }}</a></h5>
                                    <div class="blog_date">{{ service.created_at }}</div>
                                </div>
                            </div>
                        {% endfor %}
                    
                    </div>
                    

                </div>
            </div>
        </div>
    </div>
    <!-- blog wrapper end -->
    
    <!-- edu letter wrapper Start -->
    <div class="edu_letter_main_wrapper float_left">
        <div class="container">
            <div class="edu_left_envo">
                <img src="images/innn.png" alt="img">
                <h3>Sign Up for Newsletter</h3>
            </div>
            <div class="edu_right_form">
                <input type="text" placeholder="Enter your email">
                <button>Sign Up</button>
            </div>
        </div>
    </div>
    <!-- edu letter wrapper End -->
{% endblock content %}

main/templates/main/service_detail.html
{% block slider %}
{% endblock slider %}

{% block content %}
<div class="service_detail_wrapper">
    <div class="container">
        <div class="service_detail_content">
            <h1 class="service_title">{{ service.title }}</h1>
            <div class="service_image">
                <img src="{{ service.image.url }}" alt="{{ service.title }}" class="img-fluid">
            </div>
            <p class="service_description">{{ service.content }}</p>
            <h2>Book Details</h2>

            {% if service.book_image %}
                <div class="book_image">
                    <img src="{{ service.book_image.url }}" alt="Book Image" class="img-fluid">
                </div>
            {% endif %}

            {% if service.book %}
                <p class="download_link">
                    <a href="{{ service.book.file.url }}" class="btn btn-primary">Download Book</a>
                </p>
            {% endif %}
        </div>
    </div>
</div>

<style>


    .service_detail_content {
        max-width: 800px;
        max-height: auto;
        margin: 0 auto;
        background: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .service_title {
        font-size: 2.5rem;
        margin-bottom: 20px;
        color: #333;
    }

    .service_image img {
        width: 202px;
        height: 371px;
        border-radius: 8px;
        object-fit: cover;
    }

    .service_description {
        font-size: 1rem;
        margin: 20px 0;
        color: #555;
    }

    .book_image img {
        width: 100%;
        max-width: 300px;
        margin-top: 20px;
        border-radius: 8px;
    }

    .download_link {
        margin-top: 20px;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        text-decoration: none;
        font-size: 1rem;
        transition: background-color 0.3s ease;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }
</style>

{% endblock content %}

main/templates/main/teacher_detail.html
{% block slider %}
{% endblock slider %}

{% block content %}
<div class="service_detail_wrapper">
    <div class="container">
        <div class="service_detail_content">
            <h1 class="service_title">{{ teacher.title }} O'qituvchisi</h1>
            <div class="service_image">
                <img src="{{ teacher.image.url }}" alt="{{ service.title }}" class="img-fluid">
            </div>
            <p class="service_description">Ism:{{ teacher.name }}</p>
            <p class="service_description">{{ teacher.description }}</p>
            <p class="service_description">Yoshi:{{ teacher.age }}</p>
 

            
        

        </div>
    </div>
</div>

<style>


    .service_detail_content {
        max-width: 800px;
        max-height: auto;
        margin: 0 auto;
        background: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .service_title {
        font-size: 2.5rem;
        margin-bottom: 20px;
        color: #333;
    }

    .service_image img {
        width: 202px;
        height: 371px;
        border-radius: 8px;
        object-fit: cover;
    }

    .service_description {
        font-size: 1rem;
        margin: 20px 0;
        color: #555;
    }

    .book_image img {
        width: 100%;
        max-width: 300px;
        margin-top: 20px;
        border-radius: 8px;
    }

    .download_link {
        margin-top: 20px;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        text-decoration: none;
        font-size: 1rem;
        transition: background-color 0.3s ease;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }
</style>

{% endblock content %}

main/templates/main/teachers.html
{% extends 'base.html' %}

{% block slider %}
{% endblock slider %}

{% block content %}
    <!-- inner header wrapper start -->
    <div class="page_title_section float_left">
        <div class="page_header">
            <div class="container">
                <div class="row">
                    <!-- section_heading start -->
                    <div class="col-lg-12 col-md-12 col-12 col-sm-12">
                        <h1>Teachers</h1>
                    </div>
                    <div class="col-lg-12 col-md-12 col-12 col-sm-12">
                        <div class="sub_title_section">
                            <ul class="sub_title">
                                <li><a href="{% url 'main:home' %}">Home</a> &nbsp;&nbsp;&nbsp; &gt; &nbsp;&nbsp;</li>
                                <li>Teachers</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- inner header wrapper end -->
    
    <!-- blog wrapper start -->
    <div class="blog_wrapper float_left">
        <div class="container">
            <div class="row">
                <div class="col-xl-8 col-lg-8 col-md-12 col-sm-12 col-xs-12">
                    <div class="row">
                        {% for teacher in teachers %}
                             
                        
                        <div class="col-md-6">
                            <div class="blog-post-wrapper iner_blog">
                                <div class="post-thumbnail">
                                    <img src="{{ teacher.image.url }}" class="img-responsive" alt="Image">
                                </div>
                                <div class="blog-content edu_service_header">
                                    <header class="entry-header">
                                        <h4 class="entry-title edu_service_heading">
                                            <a href="#">{{ teacher.title }}</a>
                                        </h4>
                                    </header>
                                    <div class="entry-content">
                                        <p>{{ teacher.description|truncatewords:10 }}</p>
                                    </div>
                                    <a href="{% url 'main:teacher_detail' pk=teacher.pk %}">Teacher Detail</a>
                                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                
                <!-- Sidebar -->
 
            </div>
        </div>
    </div>
    <!-- blog wrapper end -->
    
    <!-- edu letter wrapper Start -->
    <div class="edu_letter_main_wrapper float_left">
        <div class="container">
            <div class="edu_left_envo">
                <img src="images/innn.png" alt="img">
                <h3>Sign Up for Newsletter</h3>
            </div>
            <div class="edu_right_form">
                <input type="text" placeholder="Enter your email">
                <button>Sign Up</button>
            </div>
        </div>
    </div>
    <!-- edu letter wrapper End -->
{% endblock content %}